### PR TITLE
refact: reworks test framework integration

### PR DESCRIPTION
**Pull request by pftg**
1. Mock Capybara's approach to the setup project. 
2. Compressing the namespace path and dropping extra 2 nested modules
3. Reduced dependency on the dynamic value constant
4. Reduced minitest dependency if you are using RSpec
5. Upgraded minitest with fixed version

### CODE REVIEW

**Comment by pftg** [comment]
@UweKubosch @donv please check I'd like to merge it and release a new major version because I started changing a high-order API from `Capyabra::Screenshot::Diff` to your original version `CapybaraScreenshotDiff`

**Comment by donv** [comment]
Two checks failing.  Can you fix?
Generally it looks good.  I'll look deeper when the check succeed.
The changes downplay the use case of using the gem without doing diffs, just take screenshots.  OK by me.

**Comment by pftg** [comment]
Exactly I want to separate the two functions and extract them to separate
gem image comparison


*Paul Keen* // Blog: https://jtway.co
<https://jtway.co/?utm_source=email&utm_medium=signature>


Uwe Kubosch ***@***.***> schrieb am Mo. 15. Juli 2024 um
10:15:

**Comment by donv** [comment]
Got a suggestion of a better name for the organization?

**Comment by pftg** [comment]
Will send you some options later today


*Paul Keen* // Blog: https://jtway.co
<https://jtway.co/?utm_source=email&utm_medium=signature>


Uwe Kubosch ***@***.***> schrieb am Mo. 15. Juli 2024 um
10:35:

**Comment by pftg** [comment]
ok, I got some bug with drivers not related to those changes will add hotfix

**Pull request closed without merging**
